---
- name: Restarted DHCP
  service:
    name: dhcpd 
    enabled: true 
    state: restarted 

- name: Restarted Firewalld
  service: 
    name: firewalld 
    state: restarted

- name: Restarted isc-dhcp-server
  service:
    name: isc-dhcp-server 
    enabled: true 
    state: restarted     