---
- name: Install and configure DHCP Server on CentOS
  include_tasks: centos_dhcp.yaml
  when:
    - ansible_os_family == 'RedHat'

- name: Install and configure DHCP Server on Debian
  include_tasks: debian_dhcp.yaml
  when:
    - ansible_os_family == 'Debian'